[project]
name = "cot-consistency"
version = "0.1.0"
description = "Medical diagnostic system using cognitive architecture"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "rich>=14.2.0",
    "typing-extensions>=4.7.0",
    "python-dotenv>=1.0.0",
]
